### ISSUE TITLE
Documentation for `branch` with no condition

### ISSUE THREAD

**Issue by ziproot** [endless-sky/endless-sky-wiki#11]
## Describe the issue

Multiple people have wondered why you cannot use `goto` without a text. Apparently, you don’t need to, because you can just use `branch` without a condition. This is not documented.

## Expected content
Information is given on how using `branch` without a condition is treated as `goto` without text attached.

**Comment by Amazinite** [comment]
That sounds more like an emergent property than anything that was ever intended. Cool use of `branch`.
