### ISSUE TITLE
Labels to organize pull requests

### ISSUE THREAD

**Issue by mOctave** [endless-sky/endless-sky-wiki#27]
So, looking through this repository, I've noticed that we have had 20 new PRs in the last month, and only 1 merged. This seems to be in part because a lot of the PRs are linked to another PR in the main game repo, which are still open over there. The problem is that a lot of fairly small typo fix PRs in the last week or two have also been lost in the pile of PR-related ones, and there's no easy way to tell them apart.

I propose a system of labels, maybe `typo`, `long-text`, and `mechanics-change` or something along those lines, so we can differentiate between different kinds of PR.

**Comment by TheGiraffe3** [comment]
Yes. In particular #26, #25, #23, #19, #18 need attention.

**Comment by mOctave** [comment]
Now that we have `enhancement` and `standalone`, should I close this?

**Comment by tibetiroka** [comment]
If you feel like we have everything we need, sure.

**Comment by mOctave** [comment]
I think we do, although more might be useful in the future.
