### ISSUE TITLE
Documentation for `tribute` player condition

### ISSUE THREAD

**Issue by ziproot** [endless-sky/endless-sky-wiki#5]
## Describe the issue

The wiki does not describe the `tribute` player condition in https://github.com/endless-sky/endless-sky/wiki/Player-Conditions.

## Expected content

A description of the `tribute` player condition in https://github.com/endless-sky/endless-sky/wiki/Player-Conditions.

**Comment by Amazinite** [comment]
Handled by https://github.com/endless-sky/endless-sky-wiki/commit/4ef68ad9e998d5cd271fda2acca00269df4c62ee.
