### ISSUE TITLE
Updated documentation describing the tier system

### ISSUE THREAD

**Issue by ziproot** [endless-sky/endless-sky-wiki#6]
### Describe the issue

The [tier system](https://github.com/endless-sky/endless-sky/wiki/StoryIdeas) listed by the GitHub wiki doesn't mention new races, such as the Bunrodea or Gegno. It also may have incorrect information on groups such as the Korath Exiles/Efreti (now considered T1.5), Remnant (now considered T1.8) or Hai (now considered T1.2), as per the Fandom wiki.

### Expected content

Information is given on the tiers of the Bunrodea and Gegno, and tier information on the Hai, Remnant, and Korath Exiles/Efreti is updated.

**Comment by Zitchas** [comment]
I continue to maintain that the tier system should be deleted entirely. We're better off without it; and it's the source of way too many arguments.

**Comment by ziproot** [comment]
I continue to maintain that the tier system is fine as long as tiers are used as data rather than as guidelines, hence why I think they should be updated.

**Comment by Quantumshark** [comment]
We're also missing the Gegno and Bunrodea from this list. I'll open a PR to update it later today.

**Comment by Zitchas** [comment]
> I continue to maintain that the tier system is fine as long as tiers are used as data rather than as guidelines, hence why I think they should be updated.

And that's the problem. There's a strong drive to use them as *rules,* and that is unacceptable.
