### ISSUE TITLE
ship personality that scans for drugs not mentioned.

### ISSUE THREAD

**Issue by itsportspe** [endless-sky/endless-sky-wiki#67]
in ship personalities it doesn't say which personality determines if the ship scans and fines you for carrying anything illegal.

**Comment by TheGiraffe3** [comment]
The personality is `surveillance`?

**Comment by itsportspe** [comment]
I look at `surveillance` but it didn't say anything about looking for drugs, or giving out fines.

**Comment by TheGiraffe3** [comment]
> I looked at `surveillance` but it didn't say anything about looking for drugs, or giving out fines.

`surveillance` makes ships scan. If a ship finds something illegal while scanning, it'll issue a fine.

**Comment by itsportspe** [comment]
thanks
