### ISSUE TITLE
`non-blocking` is undefined

### ISSUE THREAD

**Issue by ziproot** [endless-sky/endless-sky-wiki#82]
https://github.com/endless-sky/endless-sky/commit/934426fdbb76f6ca903d8199f824179a06d1566e added tbe `non-blocking` tag, but the wiki was never updated to reflect this. The `non-blocking` tag should be defined in [CreatingMissions](https://github.com/endless-sky/endless-sky/wiki/CreatingMissions).

**Comment by warp-core** [comment]
https://github.com/endless-sky/endless-sky-wiki/commit/78a1e04fe95216c7da2f01d435427b8a964581a9
Done
